# pnpm workspace configuration
packages:
  - "angular-shell"
  - "Scramble-Words"
  - "life-goals"
  - "quiz-game"
  - "life-milestone-race"
  - "retirement-readiness-journey"
  - "retirement-sudoku"
  - "financial-tetris"
  - "Tile-Flipping-game"
  - "life-shield-bomber"
  - "Snake-Life"
  - "secure-saga"
  - "life-snakes-ladders"
  - "life-flight"
  - "one-life"
  - "life-sorted"
  - "tower-defense"
  - "stackibility-stack"
  - "health-shield"
  - "life-goals-bubble-shooter"
  - "cover-word-rescue"
  - "debt-defender"
  - "shield-marble-vita"
  - "ulip-picture-puzzle"
  - "ulip-wealth-whacker"
  - "whole-life-galaga"
  - "future-climb"
  - "fortune-slice"
  - "legacy-sweep"
  - "future-sprint"
  - "guardian-grid"
  - "guardian-strike"
  - "jumbled-quest"
