# pnpm workspace configuration
packages:
  - "angular-shell"
  - "Scramble-Words"
  - "life-goals"
  - "quiz-game"
  - "life-milestone-race"
  - "retirement-readiness-journey"
  - "retirement-sudoku"
  - "financial-tetris"
  - "Tile-Flipping-game"
  - "life-shield-bomber"
  - "Snake-Life"
  - "secure-saga"
